@startuml
:Client: as C
:Empleat: as E
(Identificar-se) as I

C --> I
I <.. (Canviar el pin) : include
I <.. (Treure diners) : include
I <.. (Consultar el saldo) : include
I <.. (Consultar els últims moviments): include
E --> (Reposa diners)
@enduml
