@startuml

:Administrador: as Admin
(Crear projecte) as add
(Eliminar projecte) as del
(Actualitzar projecte) as upd
(Enviar emails) as sendMail
(Buscar projecte) as search


Admin --> add
Admin --> del
Admin --> upd


del ..> search : include
upd ..> search : include

upd <.. (Canviar informació sobre les tasaques) : extends
upd <.. (Canviar els recursos associats) : extends

Admin --> sendMail

@enduml